diagnostico:
    path:  /
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:index" }

diagnostico_show:
    path:  /{id}/show
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:show" }

diagnostico_new:
    path:  /new
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:new" }

diagnostico_create:
    path:  /create
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:create" }
    requirements: { methods: post }

diagnostico_edit:
    path:  /{id}/edit
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:edit" }

diagnostico_update:
    path:  /{id}/update
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:update" }
    requirements: { methods: post|put }

diagnostico_delete:
    path:  /{id}/delete
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:delete" }
    requirements: { methods: post|delete }

diagnostico_crear_ordentrabajo:
    path:  /{id}/crearOrden
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:crearOrden" }

diagnostico_ajax_reporte_autobus:
  path: /select_reporte_autobus
  defaults: { _controller: "BusetaTallerBundle:Diagnostico:select_reporte_autobus" }
  requirements: { methods: "GET" }
  options:
      expose: true

diagnostico_ajax_ordentrabajo_autobus:
  path: /select_diagnostico_ordentrabajo
  defaults: { _controller: "BusetaTallerBundle:Diagnostico:select_diagnostico_ordentrabajo" }
  requirements: { methods: "GET" }
  options:
      expose: true

procesarDiagnostico:
    path:  /{id}/procesarDiagnostico
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:procesarDiagnostico" }

cancelarDiagnostico:
    path:  /{id}/cancelarDiagnostico
    defaults: { _controller: "BusetaTallerBundle:Diagnostico:cancelarDiagnostico" }
