<?php

namespace Buseta\TransitoBundle\Entity\Repository;

/**
 * JuicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuicioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAccOrderedByDate($accidente)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT j FROM BusetaTransitoBundle:Juicio j
                 WHERE j.accidente = :accidente ORDER BY j.fechaFin DESC
                '
            )->setParameter('accidente', $accidente)
            ->getResult();
    }
}
