<?php

namespace Buseta\TransitoBundle\Entity\Repository;

/**
 * JuicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuicioRepository extends \Doctrine\ORM\EntityRepository
{
}
