<?php

namespace Buseta\TransitoBundle\Entity\Repository;

/**
 * PenalAccidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenalAccidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
