buseta_transito:
    resource: "@BusetaTransitoBundle/Resources/config/routing.yml"
    prefix:   /

buseta_combustible:
    resource: "@BusetaCombustibleBundle/Resources/config/routing.yml"
    prefix:   /

hatuey_soft_sequence:
    resource: "@HatueySoftSequenceBundle/Resources/config/routing.yml"
    prefix:   /

buseta_template:
    resource: "@BusetaTemplateBundle/Resources/config/routing.yml"
    prefix:   /

buseta_bodega:
    resource: "@BusetaBodegaBundle/Resources/config/routing.yml"

buseta_taller:
    resource: "@BusetaTallerBundle/Resources/config/routing.yml"

buseta_buses:
    resource: "@BusetaBusesBundle/Resources/config/routing.yml"

hatueysoft_security:
    resource: "@HatueySoftSecurityBundle/Resources/config/routing.yml"
    prefix:   /security

hatueysoft_menu:
    resource: "@HatueySoftMenuBundle/Resources/config/routing.yml"

buseta_configuration:
    resource: "@HatueySoftSequenceBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

core:
    resource: "@CoreBundle/Resources/config/routing.yml"

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /data

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /nomenclador

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
