security:
    access_decision_manager:
        strategy:             affirmative

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512
            iterations: 1000


    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    combustible:  { password: "cxydUKpoRLTX3HAEg5l87EF+m2AY8rTCseguukFdTl/IT8jZ9+v6jkDoYCFb673+b8pwk9nFfNBoHfSvb09EGg==", roles: [ 'ROLE_COMBUSTIBLE' ] }
                    bodeguero:  { password: "A55v0B2IHnchC0oyOafaGr+M9eMs43BfYHznuPp7mwECuSpBlpXZaqlkHs933RWrAqZ61ktSOb0nQOcf57xdpQ==", roles: [ 'ROLE_BODEGUERO' ] }
                    admin: { password: "Oob0FmH8l5IkiIuMaHmbxA2SrO/6o3yiRCtIs4JS7ZWBHirzUZwxCWbSLVbGT+f3H8cqUIcta5hkWfmo/+LJgA==", roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: "ZTNGCB5tk7EEQpGUjNYVGxMqrncFXhqHtR5Ty7laO4VxaaodraPI4rppc95RnGFDNIfo/ZHvppfF+lteLmJY1A==", roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false
        secured_area:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_provider: security.csrf.token_manager
            logout: ~
            anonymous: ~
            http_basic: ~
