<?php

namespace HatueySoft\NotificacionesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificacionSMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionSMSRepository extends EntityRepository
{
}
