transito_principal:
    path:  /modulo/transito
    defaults: { _controller: "BusetaTransitoBundle:Transito:principal" }

BusetaTransitoBundle_transito:
        resource: "@BusetaTransitoBundle/Resources/config/routing/transito.yml"
        prefix:   /transito

buseta_transito_multa:
  resource: "@BusetaTransitoBundle/Controller/MultaController.php"
  type:     annotation

buseta_transito_accidente:
  resource: "@BusetaTransitoBundle/Controller/AccidenteController.php"
  type:     annotation