services:
#    buseta_transito.example:
#        class: Buseta\TransitoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
        transito.transito_multa.type:
                class: Buseta\TransitoBundle\Form\Type\MultaType
                tags:
                    - {name: form.type, alias: 'transito_multa'}